fail if the same cluster is imported with different domain name

diff --git a/k8s-gke/Makefile b/k8s-gke/Makefile
--- a/k8s-gke/Makefile
+++ b/k8s-gke/Makefile
@@ -60,7 +60,16 @@ gcontext:
 	$(gcloud) container clusters get-credentials $(CLUSTER_NAME) $(LOCATION_KIND) $(TF_VAR_location)
 .PHONY: gcontext
 
-createsa: gcontext
+check:
+	$(eval EXISTING_DOMAIN:=$(shell $(kubectl) get stackinfo asi-metadata -o json | jq -r .spec.domainName))
+	@if [ "$(EXISTING_DOMAIN)" != "" ] && [ "$(EXISTING_DOMAIN)" != "$(DOMAIN_NAME)" ]; then\
+    echo "Error: This cluster has already been imported using domain name: $(EXISTING_DOMAIN)";\
+		echo "Error: Change of the domain name is not supported. This deployment will fail...";\
+		exit 1;\
+  fi
+.PHONY: check
+
+createsa: gcontext check
 	$(kubectl) get -n default serviceaccount $(SERVICE_ACCOUNT) || \
 		($(kubectl) create -n default serviceaccount $(SERVICE_ACCOUNT) && sleep 7)
 	$(kubectl) get clusterrolebinding $(SERVICE_ACCOUNT)-cluster-admin-binding || \
diff --git a/k8s-openshift/Makefile b/k8s-openshift/Makefile
--- a/k8s-openshift/Makefile
+++ b/k8s-openshift/Makefile
@@ -71,6 +71,15 @@ account:
 		$(oc) adm policy add-scc-to-group $(ASI_SCC) system:serviceaccounts:applications; \
 	fi
 
+check:
+	$(eval EXISTING_DOMAIN:=$(shell $(oc) get stackinfo asi-metadata -o json | jq -r .spec.domainName))
+	@if [ "$(EXISTING_DOMAIN)" != "" ] && [ "$(EXISTING_DOMAIN)" != "$(DOMAIN_NAME)" ]; then\
+    echo "Error: This cluster has already been imported using domain name: $(EXISTING_DOMAIN)";\
+		echo "Error: Change of the domain name is not supported. This deployment will fail...";\
+		exit 1;\
+  fi
+.PHONY: check
+
 patch:
 	echo "Disable default storageclass (if exists)"
 	-$(oc) patch storageclass gp2 -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "false"}}}'
@@ -129,7 +138,7 @@ output:
 	@echo sa_token=$(TOKEN)
 	@echo
 
-deploy: account patch storage token init vars plan apply output
+deploy: account check patch storage token init vars plan apply output
 
 undeploy: DISCOVERY_KUBE_CTX:=--context=$(DOMAIN_NAME)
 undeploy: init vars destroy apply
