Harbor: bug fixes, idempotence

diff --git a/harbor/Makefile b/harbor/Makefile
--- a/harbor/Makefile
+++ b/harbor/Makefile
@@ -11,53 +11,57 @@ export TF_DATA_DIR        ?= .terraform
 export HELM_HOME ?= $(shell pwd)/.helm
 
 NGINX_CHART ?= stable/nginx-ingress
-NGINX_CHART_VERSION ?= 0.1.1
+NGINX_CHART_VERSION ?= 0.26.0
+HARBOR_CHART_VERSION ?= 0.2.0
+TIMEOUT     ?= 600
 
 export TF_VAR_nginx_service_name ?= nginx-nginx-ingress-controller
 
 terraform ?= terraform-v0.11
-helm ?= helm --kube-context="$(TF_VAR_domain_name)" --tiller-namespace="$(TF_VAR_namespace)"
+helm ?= helm --kube-context="$(TF_VAR_domain_name)" --tiller-namespace="kube-system"
 kubectl ?= kubectl --context="$(TF_VAR_domain_name)" --namespace="$(TF_VAR_namespace)"
 git ?= git
 
 init:
-	- $(kubectl) create namespace $(TF_VAR_namespace)
+	-$(kubectl) create namespace $(TF_VAR_namespace)
+	@rm -rf harbor-helm
 	@mkdir -p charts
-	$(terraform) init -get=true -force-copy $(CLI_ARGS) \
-        -backend=true -reconfigure \
-        -backend-config="bucket=$(STATE_BUCKET)" \
-        -backend-config="region=$(STATE_REGION)" \
-        -backend-config="key=$(TF_VAR_domain_name)/s3-bucket/$(TF_VAR_component)/terraform.tfstate" \
-        -backend-config="profile=$(AWS_PROFILE)"
+	@mkdir -p .terraform
 .PHONY: init	
 
 harbor: 
 	$(helm) init --client-only --upgrade --wait
 	$(git) clone https://github.com/goharbor/harbor-helm
 	$(helm) dependency update harbor-helm
-	$(helm)	install harbor-helm \
-	    --name $(TF_VAR_component) \
-		--namespace $(TF_VAR_namespace) \
-		--replace \
-		--wait \
-		-f values-harbor.yaml
+	$(helm) list -q | grep -E '^$(TF_VAR_component)$$' || \
+		$(helm)	install harbor-helm \
+		    --name $(TF_VAR_component) \
+			--namespace $(TF_VAR_namespace) \
+			--wait \
+			--version $(HARBOR_CHART_VERSION) \
+			--values values-harbor.yaml
 .PHONY: harbor
 
 nginx:
 	$(helm) fetch \
 		--destination charts \
-		--untar $(NGINX_CHART) \
-		--version $(NGINX_CHART_VERSION)
-	$(helm) install charts/$(notdir $(NGINX_CHART)) \
-		--name nginx \
-		--namespace $(TF_VAR_namespace) \
-		--replace \
-		--wait \
-		--values values-nginx.yaml \
-		--version $(NGINX_CHART_VERSION)		
+		--untar $(NGINX_CHART)
+	$(helm) list -q | grep -E '^nginx$$' || \
+		$(helm) install charts/$(notdir $(NGINX_CHART)) \
+			--name nginx \
+			--namespace $(TF_VAR_namespace) \
+			--wait \
+			--version $(NGINX_CHART_VERSION) \
+			--values values-nginx.yaml	
 .PHONY: nginx
 
 plan:
+	$(terraform) init -get=true -force-copy $(CLI_ARGS) \
+        -backend=true -reconfigure \
+        -backend-config="bucket=$(STATE_BUCKET)" \
+        -backend-config="region=$(STATE_REGION)" \
+        -backend-config="key=$(TF_VAR_domain_name)/s3-bucket/$(TF_VAR_component)/terraform.tfstate" \
+        -backend-config="profile=$(AWS_PROFILE)"
 	$(terraform) plan $(TF_OPTS) -refresh=true -module-depth=-1 -out=.terraform/terraform.tfplan
 .PHONY: plan
 
@@ -70,13 +74,37 @@ zone:
 	$(MAKE) apply
 .PHONY: zone
 
+clean:
+	@rm -rf .helm
+	@rm -rf .terraform
+	@rm -rf charts
+	@rm -rf harbor-helm
+.PHONY: clean	
+
 deploy: init harbor nginx zone
 
-undeploy: init
-	TF_OPTS=-destroy
-	$(MAKE) plan
-	$(MAKE) apply
-	$(helm) delete --purge nginx
-	$(helm) delete --purge $(TF_VAR_component)
+undeploy:
+	-$(MAKE) plan TF_OPTS="$(TF_OPTS) -destroy"
+	-$(MAKE) apply
+	-$(helm) delete --purge nginx
+	-$(helm) delete --purge $(TF_VAR_component)
+	-$(MAKE) wait_shutdown
+	-$(kubectl) delete namespace $(TF_VAR_namespace)
 .PHONY: undeploy
+
+wait_shutdown:
+	$(eval timeout=$(shell echo "`date +%s` + $(TIMEOUT)" | bc ))
+	$(eval get_pod=$(kubectl) get pods --no-headers -l 'release=harbor' --output=json)
+	@ printf "Waiting for Harbor pods to terminate"
+
+	@ while [ `date +%s` -le "$(timeout)" ]; do \
+		if [[ -z `$(get_pod) | jq -c '.items[].spec.containers'` ]]; then \
+			echo " done"; \
+			exit 0; \
+		fi; \
+		printf "."; \
+		sleep 8; \
+	done; \
+	echo " ERROR timeout $(TIMEOUT)sec"; \
+	exit 1	
 
