Makefile:78: *** missing separator.  Stop.

diff --git a/vault/Makefile b/vault/Makefile
--- a/vault/Makefile
+++ b/vault/Makefile
@@ -75,7 +75,10 @@ auth:
 connect:
 	@$(MAKE) disconnect
 	$(eval VAULT_POD=$(shell $(kubectl) get pods -l app=vault,release=$(COMPONENT_NAME) --output=jsonpath={.items..metadata.name}))
-ifneq($(VAULT_POD),)
+	if test -z "$(VAULT_POD)"; then \
+    	echo "ERROR: Cannot find running Vault in the cluster"; \
+    	exit 1; \
+    fi
 	@echo Start proxy to pod/$(VAULT_POD)
 	nohup $(kubectl) port-forward $(VAULT_POD) $(VAULT_LOCAL_PORT):$(VAULT_PORT) &
 	@sleep 2
@@ -87,17 +90,13 @@ ifneq($(VAULT_POD),)
 		echo "Waiting for pod/$(VAULT_POD) to connect ($$i)..."; \
 		sleep 3; \
 	done; \
-	echo "Timeout for pod/$(VAULT_POD)"; \
-	exit 1
-else
-	echo "ERROR: Cannot find running vault in the cluster"
-	exit 1
-endif 
+	@echo "Timeout for pod/$(VAULT_POD)"; \
+	@exit 1
 .PHONY: connect
 
 disconnect:
 	@echo Drop connection to vault pod
-	@kill $(shell ps aux | grep -E "kubectl*|port-forward*|$(VAULT_LOCAL_PORT):$(VAULT_PORT)" | grep -v grep | awk '{print $$2}' | xargs) | true
+	-@ps aux | grep -E "kubectl*|port-forward*|$(VAULT_LOCAL_PORT):$(VAULT_PORT)" | grep -v grep | awk '{print $$2}' | xargs kill
 .PHONY: disconnect
 
 clean:
