added a wait loop for kafka quorum/config #312

diff --git a/kafka/Makefile b/kafka/Makefile
--- a/kafka/Makefile
+++ b/kafka/Makefile
@@ -5,12 +5,13 @@ DOMAIN_NAME    ?= dev.kubernetes.delivery
 NAMESPACE      ?= kafka
 CHART_VERSION  ?= 0.20.1
 REPO           ?= kafka
+TIMEOUT        ?= 600
 export HELM_HOME ?= $(shell pwd)/.helm
 
 kubectl ?= kubectl --context="$(DOMAIN_NAME)" --namespace="$(NAMESPACE)"
 helm    ?= helm --kube-context="$(DOMAIN_NAME)" --tiller-namespace="kube-system"
 
-deploy: clean init fetch purge install
+deploy: clean init fetch purge install wait
 
 init:
 	@mkdir -p $(HELM_HOME) charts
@@ -31,6 +32,24 @@ install:
 			--namespace $(NAMESPACE) \
 			--replace \
 			--values values.yaml
+
+wait:
+	$(eval timeout=$(shell echo "`date +%s` + $(TIMEOUT)" | bc ))
+	@ echo "Waiting for the zookeeper and kafka replicas to stabilize"
+	@ while [ `date +%s` -le "$(timeout)" ]; do \
+		status=`$(kubectl) -n $(NAMESPACE) get job -o jsonpath='{.items[0].status.succeeded}'`; \
+		if [ "$$status" == "1" ]; then \
+			echo " done"; \
+			exit 0; \
+		elif [ "$$status" == "0" ]; then \
+			echo " deployment failed"; \
+			exit 1; \
+		fi; \
+	printf "."; \
+	sleep 8; \
+	done; \
+	echo " ERROR timeout $(TIMEOUT)sec"; \
+	exit 1
 
 undeploy: init
 	$(helm) list -q --namespace $(NAMESPACE) | grep -E '^$(COMPONENT_NAME)$$' && \
